// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package mplcore

// Account discriminators
var ()

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_CreateV1                                   = [1]byte{0}
	Instruction_CreateCollectionV1                         = [1]byte{1}
	Instruction_AddPluginV1                                = [1]byte{2}
	Instruction_AddCollectionPluginV1                      = [1]byte{3}
	Instruction_RemovePluginV1                             = [1]byte{4}
	Instruction_RemoveCollectionPluginV1                   = [1]byte{5}
	Instruction_UpdatePluginV1                             = [1]byte{6}
	Instruction_UpdateCollectionPluginV1                   = [1]byte{7}
	Instruction_ApprovePluginAuthorityV1                   = [1]byte{8}
	Instruction_ApproveCollectionPluginAuthorityV1         = [1]byte{9}
	Instruction_RevokePluginAuthorityV1                    = [1]byte{10}
	Instruction_RevokeCollectionPluginAuthorityV1          = [1]byte{11}
	Instruction_BurnV1                                     = [1]byte{12}
	Instruction_BurnCollectionV1                           = [1]byte{13}
	Instruction_TransferV1                                 = [1]byte{14}
	Instruction_UpdateV1                                   = [1]byte{15}
	Instruction_UpdateCollectionV1                         = [1]byte{16}
	Instruction_CompressV1                                 = [1]byte{17}
	Instruction_DecompressV1                               = [1]byte{18}
	Instruction_Collect                                    = [1]byte{19}
	Instruction_CreateV2                                   = [1]byte{20}
	Instruction_CreateCollectionV2                         = [1]byte{21}
	Instruction_AddExternalPluginAdapterV1                 = [1]byte{22}
	Instruction_AddCollectionExternalPluginAdapterV1       = [1]byte{23}
	Instruction_RemoveExternalPluginAdapterV1              = [1]byte{24}
	Instruction_RemoveCollectionExternalPluginAdapterV1    = [1]byte{25}
	Instruction_UpdateExternalPluginAdapterV1              = [1]byte{26}
	Instruction_UpdateCollectionExternalPluginAdapterV1    = [1]byte{27}
	Instruction_WriteExternalPluginAdapterDataV1           = [1]byte{28}
	Instruction_WriteCollectionExternalPluginAdapterDataV1 = [1]byte{29}
	Instruction_UpdateV2                                   = [1]byte{30}
	Instruction_ExecuteV1                                  = [1]byte{31}
	Instruction_UpdateCollectionInfoV1                     = [1]byte{32}
	Instruction_AddCollectionsToGroupV1                    = [1]byte{33}
	Instruction_RemoveCollectionsFromGroupV1               = [1]byte{34}
	Instruction_AddAssetsToGroupV1                         = [1]byte{35}
	Instruction_RemoveAssetsFromGroupV1                    = [1]byte{36}
	Instruction_AddGroupsToGroupV1                         = [1]byte{37}
	Instruction_RemoveGroupsFromGroupV1                    = [1]byte{38}
	Instruction_CreateGroupV1                              = [1]byte{39}
	Instruction_CloseGroupV1                               = [1]byte{40}
	Instruction_UpdateGroupV1                              = [1]byte{41}
)
