// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package mpltokenmetadata

// Account discriminators
var ()

// Event discriminators
var ()

// Instruction discriminators
var (
	Instruction_CreateMetadataAccount                                     = [1]byte{0}
	Instruction_UpdateMetadataAccount                                     = [1]byte{1}
	Instruction_DeprecatedCreateMasterEdition                             = [1]byte{2}
	Instruction_DeprecatedMintNewEditionFromMasterEditionViaPrintingToken = [1]byte{3}
	Instruction_UpdatePrimarySaleHappenedViaToken                         = [1]byte{4}
	Instruction_DeprecatedSetReservationList                              = [1]byte{5}
	Instruction_DeprecatedCreateReservationList                           = [1]byte{6}
	Instruction_SignMetadata                                              = [1]byte{7}
	Instruction_DeprecatedMintPrintingTokensViaToken                      = [1]byte{8}
	Instruction_DeprecatedMintPrintingTokens                              = [1]byte{9}
	Instruction_CreateMasterEdition                                       = [1]byte{10}
	Instruction_MintNewEditionFromMasterEditionViaToken                   = [1]byte{11}
	Instruction_ConvertMasterEditionV1ToV2                                = [1]byte{12}
	Instruction_MintNewEditionFromMasterEditionViaVaultProxy              = [1]byte{13}
	Instruction_PuffMetadata                                              = [1]byte{14}
	Instruction_UpdateMetadataAccountV2                                   = [1]byte{15}
	Instruction_CreateMetadataAccountV2                                   = [1]byte{16}
	Instruction_CreateMasterEditionV3                                     = [1]byte{17}
	Instruction_VerifyCollection                                          = [1]byte{18}
	Instruction_Utilize                                                   = [1]byte{19}
	Instruction_ApproveUseAuthority                                       = [1]byte{20}
	Instruction_RevokeUseAuthority                                        = [1]byte{21}
	Instruction_UnverifyCollection                                        = [1]byte{22}
	Instruction_ApproveCollectionAuthority                                = [1]byte{23}
	Instruction_RevokeCollectionAuthority                                 = [1]byte{24}
	Instruction_SetAndVerifyCollection                                    = [1]byte{25}
	Instruction_FreezeDelegatedAccount                                    = [1]byte{26}
	Instruction_ThawDelegatedAccount                                      = [1]byte{27}
	Instruction_RemoveCreatorVerification                                 = [1]byte{28}
	Instruction_BurnNft                                                   = [1]byte{29}
	Instruction_VerifySizedCollectionItem                                 = [1]byte{30}
	Instruction_UnverifySizedCollectionItem                               = [1]byte{31}
	Instruction_SetAndVerifySizedCollectionItem                           = [1]byte{32}
	Instruction_CreateMetadataAccountV3                                   = [1]byte{33}
	Instruction_SetCollectionSize                                         = [1]byte{34}
	Instruction_SetTokenStandard                                          = [1]byte{35}
	Instruction_BubblegumSetCollectionSize                                = [1]byte{36}
	Instruction_BurnEditionNft                                            = [1]byte{37}
	Instruction_CreateEscrowAccount                                       = [1]byte{38}
	Instruction_CloseEscrowAccount                                        = [1]byte{39}
	Instruction_TransferOutOfEscrow                                       = [1]byte{40}
	Instruction_Burn                                                      = [1]byte{41}
	Instruction_Create                                                    = [1]byte{42}
	Instruction_Mint                                                      = [1]byte{43}
	Instruction_Delegate                                                  = [1]byte{44}
	Instruction_Revoke                                                    = [1]byte{45}
	Instruction_Lock                                                      = [1]byte{46}
	Instruction_Unlock                                                    = [1]byte{47}
	Instruction_Migrate                                                   = [1]byte{48}
	Instruction_Transfer                                                  = [1]byte{49}
	Instruction_Update                                                    = [1]byte{50}
	Instruction_Use                                                       = [1]byte{51}
	Instruction_Verify                                                    = [1]byte{52}
	Instruction_Unverify                                                  = [1]byte{53}
	Instruction_Collect                                                   = [1]byte{54}
	Instruction_Print                                                     = [1]byte{55}
	Instruction_Resize                                                    = [1]byte{56}
	Instruction_CloseAccounts                                             = [1]byte{57}
)
