// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains error types used to report the exact location
// (field, index, optionality) of an encoding or decoding failure.

package mpltokenmetadata

import "strconv"

type fieldError struct {
	Field string
	Err   error
}

func (e *fieldError) Error() string {
	switch nested := e.Err.(type) {
	case *fieldError:
		return e.Field + "." + nested.Error()
	case *indexError:
		return e.Field + nested.Error()
	case *optionError:
		return e.Field + "." + nested.Error()
	}
	return e.Field + ": " + e.Err.Error()
}

func (e *fieldError) Unwrap() error { return e.Err }

func newFieldError(field string, err error) error {
	if err == nil {
		return nil
	}
	return &fieldError{Field: field, Err: err}
}

type indexError struct {
	Index int
	Err   error
}

func (e *indexError) Error() string {
	prefix := "[" + strconv.Itoa(e.Index) + "]"
	switch nested := e.Err.(type) {
	case *fieldError:
		return prefix + "." + nested.Error()
	case *indexError:
		return prefix + nested.Error()
	case *optionError:
		return prefix + "." + nested.Error()
	}
	return prefix + ": " + e.Err.Error()
}

func (e *indexError) Unwrap() error { return e.Err }

func newIndexError(idx int, err error) error {
	if err == nil {
		return nil
	}
	return &indexError{Index: idx, Err: err}
}

type optionError struct {
	Field string
	Err   error
}

func (e *optionError) Error() string {
	prefix := "?" + e.Field
	switch nested := e.Err.(type) {
	case *fieldError:
		return prefix + "." + nested.Error()
	case *indexError:
		return prefix + nested.Error()
	case *optionError:
		return prefix + "." + nested.Error()
	}
	return prefix + ": " + e.Err.Error()
}

func (e *optionError) Unwrap() error { return e.Err }

func newOptionError(field string, err error) error {
	if err == nil {
		return nil
	}
	return &optionError{Field: field, Err: err}
}
