// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package associatedtokenaccount

// Instruction discriminators
var (
	Instruction_Create           = [1]byte{0}
	Instruction_CreateIdempotent = [1]byte{1}
	Instruction_RecoverNested    = [1]byte{2}
)
