// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package associatedtokenaccount

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")

const ProgramName = "AssociatedTokenAccount"

func SetProgramID(pubkey solanago.PublicKey) {
	ProgramID = pubkey
	solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

func init() {
	if !ProgramID.IsZero() {
		solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}
