// Code generated from instructions.go. DO NOT EDIT.
package token2022

func newParamsByInstructionType(t InstructionType) any {
	switch t {
	case InstructionTypeInitializeMint:
		return new(InitializeMintParams)
	case InstructionTypeInitializeAccount:
		return new(InitializeAccountParams)
	case InstructionTypeInitializeMultisig:
		return new(InitializeMultisigParams)
	case InstructionTypeTransfer:
		return new(TransferParams)
	case InstructionTypeApprove:
		return new(ApproveParams)
	case InstructionTypeRevoke:
		return new(RevokeParams)
	case InstructionTypeSetAuthority:
		return new(SetAuthorityParams)
	case InstructionTypeMintTo:
		return new(MintToParams)
	case InstructionTypeBurn:
		return new(BurnParams)
	case InstructionTypeCloseAccount:
		return new(CloseAccountParams)
	case InstructionTypeFreezeAccount:
		return new(FreezeAccountParams)
	case InstructionTypeThawAccount:
		return new(ThawAccountParams)
	case InstructionTypeTransferChecked:
		return new(TransferCheckedParams)
	case InstructionTypeApproveChecked:
		return new(ApproveCheckedParams)
	case InstructionTypeMintToChecked:
		return new(MintToCheckedParams)
	case InstructionTypeBurnChecked:
		return new(BurnCheckedParams)
	case InstructionTypeInitializeAccount2:
		return new(InitializeAccount2Params)
	case InstructionTypeSyncNative:
		return new(SyncNativeParams)
	case InstructionTypeInitializeAccount3:
		return new(InitializeAccount3Params)
	case InstructionTypeInitializeMultisig2:
		return new(InitializeMultisig2Params)
	case InstructionTypeInitializeMint2:
		return new(InitializeMint2Params)
	case InstructionTypeGetAccountDataSize:
		return new(GetAccountDataSizeParams)
	case InstructionTypeInitializeImmutableOwner:
		return new(InitializeImmutableOwnerParams)
	case InstructionTypeAmountToUIAmount:
		return new(AmountToUIAmountParams)
	case InstructionTypeUIAmountToAmount:
		return new(UIAmountToAmountParams)
	case InstructionTypeInitializeMintCloseAuthority:
		return new(InitializeMintCloseAuthorityParams)
	case InstructionTypeInitializeTransferFeeConfig:
		return new(InitializeTransferFeeConfigParams)
	case InstructionTypeTransferCheckedWithFee:
		return new(TransferCheckedWithFeeParams)
	case InstructionTypeWithdrawWithheldTokensFromMint:
		return new(WithdrawWithheldTokensFromMintParams)
	case InstructionTypeWithdrawWithheldTokensFromAccounts:
		return new(WithdrawWithheldTokensFromAccountsParams)
	case InstructionTypeHarvestWithheldTokensToMint:
		return new(HarvestWithheldTokensToMintParams)
	case InstructionTypeSetTransferFee:
		return new(SetTransferFeeParams)
	case InstructionTypeInitializeConfidentialTransferMint:
		return new(InitializeConfidentialTransferMintParams)
	case InstructionTypeUpdateConfidentialTransferMint:
		return new(UpdateConfidentialTransferMintParams)
	case InstructionTypeConfigureConfidentialTransferAccount:
		return new(ConfigureConfidentialTransferAccountParams)
	case InstructionTypeApproveConfidentialTransferAccount:
		return new(ApproveConfidentialTransferAccountParams)
	case InstructionTypeEmptyConfidentialTransferAccount:
		return new(EmptyConfidentialTransferAccountParams)
	case InstructionTypeConfidentialDeposit:
		return new(ConfidentialDepositParams)
	case InstructionTypeConfidentialWithdraw:
		return new(ConfidentialWithdrawParams)
	case InstructionTypeConfidentialTransfer:
		return new(ConfidentialTransferParams)
	case InstructionTypeApplyConfidentialPendingBalance:
		return new(ApplyConfidentialPendingBalanceParams)
	case InstructionTypeEnableConfidentialCredits:
		return new(EnableConfidentialCreditsParams)
	case InstructionTypeDisableConfidentialCredits:
		return new(DisableConfidentialCreditsParams)
	case InstructionTypeEnableNonConfidentialCredits:
		return new(EnableNonConfidentialCreditsParams)
	case InstructionTypeDisableNonConfidentialCredits:
		return new(DisableNonConfidentialCreditsParams)
	case InstructionTypeConfidentialTransferWithFee:
		return new(ConfidentialTransferWithFeeParams)
	case InstructionTypeInitializeDefaultAccountState:
		return new(InitializeDefaultAccountStateParams)
	case InstructionTypeUpdateDefaultAccountState:
		return new(UpdateDefaultAccountStateParams)
	case InstructionTypeReallocate:
		return new(ReallocateParams)
	case InstructionTypeEnableMemoTransfers:
		return new(EnableMemoTransfersParams)
	case InstructionTypeDisableMemoTransfers:
		return new(DisableMemoTransfersParams)
	case InstructionTypeCreateNativeMint:
		return new(CreateNativeMintParams)
	case InstructionTypeInitializeNonTransferableMint:
		return new(InitializeNonTransferableMintParams)
	case InstructionTypeInitializeInterestBearingMint:
		return new(InitializeInterestBearingMintParams)
	case InstructionTypeUpdateRateInterestBearingMint:
		return new(UpdateRateInterestBearingMintParams)
	case InstructionTypeEnableCpiGuard:
		return new(EnableCpiGuardParams)
	case InstructionTypeDisableCpiGuard:
		return new(DisableCpiGuardParams)
	case InstructionTypeInitializePermanentDelegate:
		return new(InitializePermanentDelegateParams)
	case InstructionTypeInitializeTransferHook:
		return new(InitializeTransferHookParams)
	case InstructionTypeUpdateTransferHook:
		return new(UpdateTransferHookParams)
	case InstructionTypeInitializeConfidentialTransferFee:
		return new(InitializeConfidentialTransferFeeParams)
	case InstructionTypeWithdrawWithheldTokensFromMintForConfidentialTransferFee:
		return new(WithdrawWithheldTokensFromMintForConfidentialTransferFeeParams)
	case InstructionTypeWithdrawWithheldTokensFromAccountsForConfidentialTransferFee:
		return new(WithdrawWithheldTokensFromAccountsForConfidentialTransferFeeParams)
	case InstructionTypeHarvestWithheldTokensToMintForConfidentialTransferFee:
		return new(HarvestWithheldTokensToMintForConfidentialTransferFeeParams)
	case InstructionTypeEnableHarvestToMint:
		return new(EnableHarvestToMintParams)
	case InstructionTypeDisableHarvestToMint:
		return new(DisableHarvestToMintParams)
	case InstructionTypeWithdrawExcessLamports:
		return new(WithdrawExcessLamportsParams)
	case InstructionTypeInitializeMetadataPointer:
		return new(InitializeMetadataPointerParams)
	case InstructionTypeUpdateMetadataPointer:
		return new(UpdateMetadataPointerParams)
	case InstructionTypeInitializeGroupPointer:
		return new(InitializeGroupPointerParams)
	case InstructionTypeUpdateGroupPointer:
		return new(UpdateGroupPointerParams)
	case InstructionTypeInitializeGroupMemberPointer:
		return new(InitializeGroupMemberPointerParams)
	case InstructionTypeUpdateGroupMemberPointer:
		return new(UpdateGroupMemberPointerParams)
	case InstructionTypeInitializeScaledUIAmountMint:
		return new(InitializeScaledUIAmountMintParams)
	case InstructionTypeUpdateMultiplierScaledUIMint:
		return new(UpdateMultiplierScaledUIMintParams)
	case InstructionTypeInitializePausableConfig:
		return new(InitializePausableConfigParams)
	case InstructionTypePause:
		return new(PauseParams)
	case InstructionTypeResume:
		return new(ResumeParams)
	case InstructionTypeInitializeTokenMetadata:
		return new(InitializeTokenMetadataParams)
	case InstructionTypeUpdateTokenMetadataField:
		return new(UpdateTokenMetadataFieldParams)
	case InstructionTypeRemoveTokenMetadataKey:
		return new(RemoveTokenMetadataKeyParams)
	case InstructionTypeUpdateTokenMetadataUpdateAuthority:
		return new(UpdateTokenMetadataUpdateAuthorityParams)
	case InstructionTypeEmitTokenMetadata:
		return new(EmitTokenMetadataParams)
	case InstructionTypeInitializeTokenGroup:
		return new(InitializeTokenGroupParams)
	case InstructionTypeUpdateTokenGroupMaxSize:
		return new(UpdateTokenGroupMaxSizeParams)
	case InstructionTypeUpdateTokenGroupUpdateAuthority:
		return new(UpdateTokenGroupUpdateAuthorityParams)
	case InstructionTypeInitializeTokenGroupMember:
		return new(InitializeTokenGroupMemberParams)
	case InstructionTypeUnwrapLamports:
		return new(UnwrapLamportsParams)
	case InstructionTypeInitializePermissionedBurn:
		return new(InitializePermissionedBurnParams)
	case InstructionTypePermissionedBurn:
		return new(PermissionedBurnParams)
	case InstructionTypePermissionedBurnChecked:
		return new(PermissionedBurnCheckedParams)
	default:
		return nil
	}
}

func newAccountsByInstructionType(t InstructionType) any {
	switch t {
	case InstructionTypeInitializeMint:
		return new(InitializeMintAccounts)
	case InstructionTypeInitializeAccount:
		return new(InitializeAccountAccounts)
	case InstructionTypeInitializeMultisig:
		return new(InitializeMultisigAccounts)
	case InstructionTypeTransfer:
		return new(TransferAccounts)
	case InstructionTypeApprove:
		return new(ApproveAccounts)
	case InstructionTypeRevoke:
		return new(RevokeAccounts)
	case InstructionTypeSetAuthority:
		return new(SetAuthorityAccounts)
	case InstructionTypeMintTo:
		return new(MintToAccounts)
	case InstructionTypeBurn:
		return new(BurnAccounts)
	case InstructionTypeCloseAccount:
		return new(CloseAccountAccounts)
	case InstructionTypeFreezeAccount:
		return new(FreezeAccountAccounts)
	case InstructionTypeThawAccount:
		return new(ThawAccountAccounts)
	case InstructionTypeTransferChecked:
		return new(TransferCheckedAccounts)
	case InstructionTypeApproveChecked:
		return new(ApproveCheckedAccounts)
	case InstructionTypeMintToChecked:
		return new(MintToCheckedAccounts)
	case InstructionTypeBurnChecked:
		return new(BurnCheckedAccounts)
	case InstructionTypeInitializeAccount2:
		return new(InitializeAccount2Accounts)
	case InstructionTypeSyncNative:
		return new(SyncNativeAccounts)
	case InstructionTypeInitializeAccount3:
		return new(InitializeAccount3Accounts)
	case InstructionTypeInitializeMultisig2:
		return new(InitializeMultisig2Accounts)
	case InstructionTypeInitializeMint2:
		return new(InitializeMint2Accounts)
	case InstructionTypeGetAccountDataSize:
		return new(GetAccountDataSizeAccounts)
	case InstructionTypeInitializeImmutableOwner:
		return new(InitializeImmutableOwnerAccounts)
	case InstructionTypeAmountToUIAmount:
		return new(AmountToUIAmountAccounts)
	case InstructionTypeUIAmountToAmount:
		return new(UIAmountToAmountAccounts)
	case InstructionTypeInitializeMintCloseAuthority:
		return new(InitializeMintCloseAuthorityAccounts)
	case InstructionTypeInitializeTransferFeeConfig:
		return new(InitializeTransferFeeConfigAccounts)
	case InstructionTypeTransferCheckedWithFee:
		return new(TransferCheckedWithFeeAccounts)
	case InstructionTypeWithdrawWithheldTokensFromMint:
		return new(WithdrawWithheldTokensFromMintAccounts)
	case InstructionTypeWithdrawWithheldTokensFromAccounts:
		return new(WithdrawWithheldTokensFromAccountsAccounts)
	case InstructionTypeHarvestWithheldTokensToMint:
		return new(HarvestWithheldTokensToMintAccounts)
	case InstructionTypeSetTransferFee:
		return new(SetTransferFeeAccounts)
	case InstructionTypeInitializeConfidentialTransferMint:
		return new(InitializeConfidentialTransferMintAccounts)
	case InstructionTypeUpdateConfidentialTransferMint:
		return new(UpdateConfidentialTransferMintAccounts)
	case InstructionTypeConfigureConfidentialTransferAccount:
		return new(ConfigureConfidentialTransferAccountAccounts)
	case InstructionTypeApproveConfidentialTransferAccount:
		return new(ApproveConfidentialTransferAccountAccounts)
	case InstructionTypeEmptyConfidentialTransferAccount:
		return new(EmptyConfidentialTransferAccountAccounts)
	case InstructionTypeConfidentialDeposit:
		return new(ConfidentialDepositAccounts)
	case InstructionTypeConfidentialWithdraw:
		return new(ConfidentialWithdrawAccounts)
	case InstructionTypeConfidentialTransfer:
		return new(ConfidentialTransferAccounts)
	case InstructionTypeApplyConfidentialPendingBalance:
		return new(ApplyConfidentialPendingBalanceAccounts)
	case InstructionTypeEnableConfidentialCredits:
		return new(EnableConfidentialCreditsAccounts)
	case InstructionTypeDisableConfidentialCredits:
		return new(DisableConfidentialCreditsAccounts)
	case InstructionTypeEnableNonConfidentialCredits:
		return new(EnableNonConfidentialCreditsAccounts)
	case InstructionTypeDisableNonConfidentialCredits:
		return new(DisableNonConfidentialCreditsAccounts)
	case InstructionTypeConfidentialTransferWithFee:
		return new(ConfidentialTransferWithFeeAccounts)
	case InstructionTypeInitializeDefaultAccountState:
		return new(InitializeDefaultAccountStateAccounts)
	case InstructionTypeUpdateDefaultAccountState:
		return new(UpdateDefaultAccountStateAccounts)
	case InstructionTypeReallocate:
		return new(ReallocateAccounts)
	case InstructionTypeEnableMemoTransfers:
		return new(EnableMemoTransfersAccounts)
	case InstructionTypeDisableMemoTransfers:
		return new(DisableMemoTransfersAccounts)
	case InstructionTypeCreateNativeMint:
		return new(CreateNativeMintAccounts)
	case InstructionTypeInitializeNonTransferableMint:
		return new(InitializeNonTransferableMintAccounts)
	case InstructionTypeInitializeInterestBearingMint:
		return new(InitializeInterestBearingMintAccounts)
	case InstructionTypeUpdateRateInterestBearingMint:
		return new(UpdateRateInterestBearingMintAccounts)
	case InstructionTypeEnableCpiGuard:
		return new(EnableCpiGuardAccounts)
	case InstructionTypeDisableCpiGuard:
		return new(DisableCpiGuardAccounts)
	case InstructionTypeInitializePermanentDelegate:
		return new(InitializePermanentDelegateAccounts)
	case InstructionTypeInitializeTransferHook:
		return new(InitializeTransferHookAccounts)
	case InstructionTypeUpdateTransferHook:
		return new(UpdateTransferHookAccounts)
	case InstructionTypeInitializeConfidentialTransferFee:
		return new(InitializeConfidentialTransferFeeAccounts)
	case InstructionTypeWithdrawWithheldTokensFromMintForConfidentialTransferFee:
		return new(WithdrawWithheldTokensFromMintForConfidentialTransferFeeAccounts)
	case InstructionTypeWithdrawWithheldTokensFromAccountsForConfidentialTransferFee:
		return new(WithdrawWithheldTokensFromAccountsForConfidentialTransferFeeAccounts)
	case InstructionTypeHarvestWithheldTokensToMintForConfidentialTransferFee:
		return new(HarvestWithheldTokensToMintForConfidentialTransferFeeAccounts)
	case InstructionTypeEnableHarvestToMint:
		return new(EnableHarvestToMintAccounts)
	case InstructionTypeDisableHarvestToMint:
		return new(DisableHarvestToMintAccounts)
	case InstructionTypeWithdrawExcessLamports:
		return new(WithdrawExcessLamportsAccounts)
	case InstructionTypeInitializeMetadataPointer:
		return new(InitializeMetadataPointerAccounts)
	case InstructionTypeUpdateMetadataPointer:
		return new(UpdateMetadataPointerAccounts)
	case InstructionTypeInitializeGroupPointer:
		return new(InitializeGroupPointerAccounts)
	case InstructionTypeUpdateGroupPointer:
		return new(UpdateGroupPointerAccounts)
	case InstructionTypeInitializeGroupMemberPointer:
		return new(InitializeGroupMemberPointerAccounts)
	case InstructionTypeUpdateGroupMemberPointer:
		return new(UpdateGroupMemberPointerAccounts)
	case InstructionTypeInitializeScaledUIAmountMint:
		return new(InitializeScaledUIAmountMintAccounts)
	case InstructionTypeUpdateMultiplierScaledUIMint:
		return new(UpdateMultiplierScaledUIMintAccounts)
	case InstructionTypeInitializePausableConfig:
		return new(InitializePausableConfigAccounts)
	case InstructionTypePause:
		return new(PauseAccounts)
	case InstructionTypeResume:
		return new(ResumeAccounts)
	case InstructionTypeInitializeTokenMetadata:
		return new(InitializeTokenMetadataAccounts)
	case InstructionTypeUpdateTokenMetadataField:
		return new(UpdateTokenMetadataFieldAccounts)
	case InstructionTypeRemoveTokenMetadataKey:
		return new(RemoveTokenMetadataKeyAccounts)
	case InstructionTypeUpdateTokenMetadataUpdateAuthority:
		return new(UpdateTokenMetadataUpdateAuthorityAccounts)
	case InstructionTypeEmitTokenMetadata:
		return new(EmitTokenMetadataAccounts)
	case InstructionTypeInitializeTokenGroup:
		return new(InitializeTokenGroupAccounts)
	case InstructionTypeUpdateTokenGroupMaxSize:
		return new(UpdateTokenGroupMaxSizeAccounts)
	case InstructionTypeUpdateTokenGroupUpdateAuthority:
		return new(UpdateTokenGroupUpdateAuthorityAccounts)
	case InstructionTypeInitializeTokenGroupMember:
		return new(InitializeTokenGroupMemberAccounts)
	case InstructionTypeUnwrapLamports:
		return new(UnwrapLamportsAccounts)
	case InstructionTypeInitializePermissionedBurn:
		return new(InitializePermissionedBurnAccounts)
	case InstructionTypePermissionedBurn:
		return new(PermissionedBurnAccounts)
	case InstructionTypePermissionedBurnChecked:
		return new(PermissionedBurnCheckedAccounts)
	default:
		return nil
	}
}
